// PDF Invoice Generator
import jsPDF from 'jspdf';
import { Invoice } from '../types';
import { format } from 'date-fns';

export function generateInvoicePDF(invoice: Invoice): void {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('BHARAT BIZ-AGENT', 105, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Your Smart Business Assistant', 105, 27, { align: 'center' });
  
  // Invoice details
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Invoice: ${invoice.invoice_number}`, 20, 40);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Date: ${format(new Date(invoice.created_at), 'dd/MM/yyyy HH:mm')}`, 20, 47);
  
  if (invoice.customer_name) {
    doc.text(`Customer: ${invoice.customer_name}`, 20, 54);
  }
  if (invoice.customer_mobile) {
    doc.text(`Mobile: ${invoice.customer_mobile}`, 20, 61);
  }
  
  // Payment status
  const statusY = invoice.customer_mobile ? 68 : 54;
  doc.setFont('helvetica', 'bold');
  const statusColor = invoice.payment_status === 'completed' ? [0, 150, 0] : 
                      invoice.payment_status === 'pending' ? [255, 100, 0] : [255, 150, 0];
  doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.text(`Status: ${invoice.payment_status.toUpperCase()}`, 20, statusY);
  doc.setTextColor(0, 0, 0);
  
  // Table header
  const tableStartY = statusY + 10;
  doc.setFillColor(240, 240, 240);
  doc.rect(20, tableStartY, 170, 8, 'F');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Item', 22, tableStartY + 5);
  doc.text('Qty', 100, tableStartY + 5);
  doc.text('Unit', 115, tableStartY + 5);
  doc.text('Price', 135, tableStartY + 5);
  doc.text('GST', 155, tableStartY + 5);
  doc.text('Total', 175, tableStartY + 5, { align: 'right' });
  
  // Table rows
  doc.setFont('helvetica', 'normal');
  let currentY = tableStartY + 8;
  
  invoice.items.forEach((item, index) => {
    if (currentY > 270) {
      doc.addPage();
      currentY = 20;
    }
    
    const rowY = currentY + 5;
    
    // Alternate row colors
    if (index % 2 === 1) {
      doc.setFillColor(250, 250, 250);
      doc.rect(20, currentY, 170, 7, 'F');
    }
    
    doc.text(item.product_name, 22, rowY);
    doc.text(item.quantity.toString(), 100, rowY);
    doc.text(item.unit, 115, rowY);
    doc.text(`₹${item.price_per_unit.toFixed(2)}`, 135, rowY);
    doc.text(`₹${item.gst_amount.toFixed(2)}`, 155, rowY);
    doc.text(`₹${item.total_price.toFixed(2)}`, 188, rowY, { align: 'right' });
    
    currentY += 7;
  });
  
  // Totals
  currentY += 5;
  doc.setDrawColor(200, 200, 200);
  doc.line(20, currentY, 190, currentY);
  
  currentY += 7;
  doc.setFont('helvetica', 'normal');
  doc.text('Subtotal:', 140, currentY);
  doc.text(`₹${invoice.subtotal.toFixed(2)}`, 188, currentY, { align: 'right' });
  
  currentY += 6;
  doc.text('Total GST:', 140, currentY);
  doc.text(`₹${invoice.total_gst.toFixed(2)}`, 188, currentY, { align: 'right' });
  
  currentY += 8;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('TOTAL AMOUNT:', 140, currentY);
  doc.text(`₹${invoice.total_amount.toFixed(2)}`, 188, currentY, { align: 'right' });
  
  // Payment details
  if (invoice.payment_mode) {
    currentY += 10;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(`Payment Mode: ${invoice.payment_mode}`, 20, currentY);
  }
  
  // UPI payment string
  if (invoice.upi_string) {
    currentY += 6;
    doc.setFontSize(8);
    doc.text('UPI Payment:', 20, currentY);
    doc.text(invoice.upi_string, 20, currentY + 4);
  }
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('Thank you for your business!', 105, 280, { align: 'center' });
  doc.text('Generated by Bharat Biz-Agent', 105, 285, { align: 'center' });
  
  // Save PDF
  doc.save(`${invoice.invoice_number}.pdf`);
}
